version: '3.7'

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2

    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - politicians-internal

    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false

  kibana:

    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

    networks:
      - politicians-internal
networks:
  politicians-internal:
    attachable: true
